# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: AMS X02 Méthodes numeriques avancées
author: Marc Massot
logo: logo_amsx02.png
copyright: "2023"

# Disable building files that aren’t in the table of contents
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 600

# Information about where the book exists on the web
#repository:
url: https://github.com/hpc-maths/jb_amsx02_2023_2024  # Online location of your book
branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  home_page_in_navbar: false

launch_buttons:
  binderhub_url: https://mybinder.org

# load require.js for plotly
sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
